# Generated by Django 3.1.2 on 2020-10-23 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseManagement', '0002_auto_20201023_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='e_mail',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='firstname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lastname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
