# Generated by Django 3.1.1 on 2020-11-10 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseManagement', '0003_auto_20201023_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('last_modified', models.DateField(auto_now_add=True)),
                ('barcode', models.CharField(max_length=200, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('restock', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True)),
                ('restock_quantity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='e_mail',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='lastname',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
