# Generated by Django 3.1.1 on 2020-10-20 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseManagement', '0005_paycheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='billmonitor',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='paycheck',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
    ]
